
version: "3.8"
services:
  backend:
    build:
      context: ./FinalProject
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/final_project_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Formation123
    depends_on:
      - db

  frontend:
    build:
      context: ./hnservices-final-project-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4500:4500"
    volumes:
      - ./HNservices-Final-project-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Formation123
      MYSQL_DATABASE: final_project_db
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge