
#FROM maven:3.8.7-eclipse-temurin-17 AS build

#WORKDIR /springboot

#COPY pom.xml /springboot
#COPY src /springboot/src

#RUN mvn clean install -DskipTests

#EXPOSE 8080

#CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=docker"]

FROM maven:3.8.7-eclipse-temurin-17 AS build
WORKDIR /app
#COPY . .
#RUN mvn clean package -DskipTests
COPY pom.xml ./
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jdk-alpine AS runtime
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]